### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by maximuml** [codeguida/vkutils#1]
Traceback (most recent call last):
  File "VKSpySystem/main.py", line 81, in <module>
    vkapi = vk.API(access_token=os.environ["token"])
  File "/usr/lib/python3.5/os.py", line 725, in **getitem**
    raise KeyError(key) from None
KeyError: 'token'

Any help????

**Comment by OlegWock** [comment]
replace `os.environ["token"]` to `'*your_token*'`

**Comment by maximuml** [comment]
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    vkapi = vk.API(access_token='1d39462f9cb916ef72eb635c5629fc4e11e428c264*******')
TypeError: **init**() missing 1 required positional argument: 'session'

**Comment by OlegWock** [comment]
`vk` module have been updated. Check the docs for latest version http://vk.readthedocs.io/en/latest/
